## Machine Learning Zoomcamp

#### 1.7 Introduction to Numpy

##### Plan:
- Creating Array
- Multi-dimensional arrays
- Randomly generated arrays
- Element-wise operations
  - Comparison operations
  - Logical operations
- Summarizing operations

In [1]:
import numpy as np
import pandas as pd

In [2]:
#pip install pandas

In [3]:
np

<module 'numpy' from 'C:\\Users\\CGX\\AppData\\Roaming\\Python\\Python37\\site-packages\\numpy\\__init__.py'>

#### Creating Arrays

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [8]:
a[2]

3

In [9]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

#### Multi-dimentional Array

In [11]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [13]:
n[1, 2] = 60

In [14]:
n

array([[ 1,  2,  3],
       [ 4,  5, 60],
       [ 7,  8,  9]])

In [15]:
n[2] = [1,1,1]

In [16]:
n

array([[ 1,  2,  3],
       [ 4,  5, 60],
       [ 1,  1,  1]])

In [17]:
n[:, 2] = [0,1,2]

In [18]:
n

array([[1, 2, 0],
       [4, 5, 1],
       [1, 1, 2]])

#### Randomly Generated Arrays

In [19]:
#Uniform Distribution
np.random.seed(2)
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [20]:
# Normal Distribution
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [21]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

#### Element-wise operations

In [22]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [23]:
a + 2

array([2, 3, 4, 5, 6])

In [24]:
b = (10 + (a + 2)) ** 2 / 100

In [25]:
b

array([1.44, 1.69, 1.96, 2.25, 2.56])

In [26]:
a + b

array([1.44, 2.69, 3.96, 5.25, 6.56])

In [27]:
a + b / 10

array([0.144, 1.169, 2.196, 3.225, 4.256])

#### Comparison Operations

In [28]:
a

array([0, 1, 2, 3, 4])

In [29]:
a >= 2

array([False, False,  True,  True,  True])

In [30]:
b

array([1.44, 1.69, 1.96, 2.25, 2.56])

In [31]:
a > b

array([False, False,  True,  True,  True])

In [32]:
a[a > b]

array([2, 3, 4])

In [33]:
b[a > b]

array([1.96, 2.25, 2.56])

#### Summarizing Operations

In [34]:
a

array([0, 1, 2, 3, 4])

In [35]:
a.mean()

2.0

In [36]:
a.std()

1.4142135623730951

In [37]:
a.min()

0

In [38]:
a.sum()

10

In [39]:
n.sum()

17